### ISSUE TITLE
Toll-free numbers

### ISSUE THREAD

**Issue by kr3wangel** [vivialconnect/vivialconnect-dotnet#2]
Issue: 
The library doesn't support buying toll-free numbers. The `FindAvailable()` method only goes through the `numbers/available/US/local.json` route. And that route does not return toll-free numbers. 

Solution:
Add support for the "Find Toll-Free numbers for purchase" (`numbers/available/US/tollfree.json`)

**Comment by nherman** [comment]
Thanks for the feedback @kr3wangel. We are looking into the issue.

**Comment by amcadoo** [comment]
@kr3wangel in the interim, feel free to purchase TF numbers _via_ the Buy Numbers tab:

![Buy_numbers](https://user-images.githubusercontent.com/22844749/134701390-912966b6-170c-4284-81fd-e931c97c0f3c.PNG)

**Comment by nherman** [comment]
Fixed issue described in original comment. Also fixed unrelated issue with local number purchase. Thanks to @magils for his help.

@kr3wangel New binary is available from nuget.org.
